name: Builds
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Buliding...
        run: ./gradlew build

      - name: Upload Jar file
        uses: actions/upload-artifact@v4
        with:
          name: "CustomDiscs"
          path: "build/libs/*.jar"
